### ISSUE TITLE
Buttons Don't appear

### ISSUE THREAD

**Issue by btd1337** [horst3180/Ceti-2-theme#12]
Buttons minimize, maximize and close don't appear in some softwares as Firefox, Ubuntu Software Center but appears in others as Nautilus.

I'm using Ubuntu Gnome 15.04 + Gnome 3.16.

![firefox](https://cloud.githubusercontent.com/assets/11943860/8018372/3cfaed6c-0bef-11e5-9d8f-e5f32989cc3a.png)
![ubuntu software center](https://cloud.githubusercontent.com/assets/11943860/8018377/4656799e-0bef-11e5-9c98-862a432b81ff.png)
![nautilus](https://cloud.githubusercontent.com/assets/11943860/8018379/4b00722e-0bef-11e5-9b32-9762f4b62b1b.png)

**Comment by horst3180** [comment]
You'll have to install the theme manually, because the deb package was built for a standard Ubuntu installation with Gnome 3.14

**Comment by btd1337** [comment]
The manual installer is with error.

![captura de tela de 2015-06-11 15-56-29](https://cloud.githubusercontent.com/assets/11943860/8115538/77789ffe-1052-11e5-8ac5-78290e2aa805.png)

**Comment by horst3180** [comment]
You have to install the build dependencies for it to work:

`sudo apt-get install autoconf automake pkg-config libgtk-3-dev`

**Comment by btd1337** [comment]
Nice! It worked!

Thanks, dude.
