### ISSUE TITLE
Alternate metacity for gnome 3.16

### ISSUE THREAD

**Issue by Nowrouz** [horst3180/Ceti-2-theme#16]
Nice as always, specially vertex cinnamon; thank you.
Would you please consider making alt-matacity for gnome 3.16?

**Comment by horst3180** [comment]
That's not possible. Gnome 3.16 doesn't use the metacity theme format anymore.

**Comment by Nowrouz** [comment]
But your Vertex has an alt-metacity and it works with gnome 3.16. (I'm using cinnamon in Debian testing branch)

**Comment by horst3180** [comment]
So, you're using Cinnamon and not Gnome. The Vertex alt-metacity theme doesn't work under Gnome 3.16 either.
Have you tried this? https://github.com/horst3180/Ceti-2-theme/tree/master/extra/Ceti-2-alternative-metacity

**Comment by Nowrouz** [comment]
Oh my poor knowledge! It works well, thank you so much!
