### ISSUE TITLE
Ceti is not working on MATE

### ISSUE THREAD

**Issue by sergioad** [horst3180/Ceti-2-theme#3]
Hello I noted that Ceti does not works on MATE, I can have the GTK widgets but the metacity toolbar is missing and I want use your GTK theme on my Fedora 21 MATE + Compiz

**Comment by horst3180** [comment]
I haven't gotten around to implement MATE support yet. I will do it, though.

**Comment by horst3180** [comment]
It took a while, but it should work now.

**Comment by nelson6e65** [comment]
I just got that I need 'gnome' icons... So I installed `gnome-themes gnome-icon-theme` and works for me!
