### ISSUE TITLE
Title bars in Gnome 3.16

### ISSUE THREAD

**Issue by ignisf** [horst3180/Ceti-2-theme#7]
Hey,

In Gnome 3.16 all apps that don't use the header bar get fitted with a big useless title bar. 

![image](https://cloud.githubusercontent.com/assets/1153188/7078129/18ac3580-df1f-11e4-9491-647c9b7b05d7.png)

Do you think it could be hidden like the title bars in 3.14?

**Comment by sladage** [comment]
I just hope there will be a 3.16 compatible version of Ceti, which is one of the most beautiful themes for Gnome.

**Comment by horst3180** [comment]
Fixed. The theme now has full 3.16 support (and has been renamed to Ceti-2).

**Comment by ignisf** [comment]
@horst3180, can you point me where should I look to style the header bars and title bars in 3.16? I've been playing around with the `.titlebar` class in `common.scss` with no effects. (I've been regenerating the css before testing with `./parse-sass.sh`)

**Comment by horst3180** [comment]
The `.titlebar` class is the right class. This is the part in `_common.scss` that styles the header bars of csd windows

    .titlebar {
      padding-left: 6px;
      padding-right: 6px;
      color: $wm_title;
      border-width: 0 0 1px;
      border-style: solid;
      border-radius: 3px 3px 0 0;
      border-color: nth($_borders_color, 2);
      background-color: transparent;
      background-image: linear-gradient(to bottom,
                                        lighten($wm_bg_a, 2%) 22%,
                                        $wm_bg_a 22%,
                                        $wm_bg_b);
      box-shadow: inset 0 1px $wm_highlight;

     .solid-csd & { box-shadow: none; }
    }

The window decorations of non-csd/ssd windows like gnome-terminal use the `.default-decoration` class. The main part of this style looks like this

    &.default-decoration {
      padding-top: 3px;	    // less padding for ssd
      padding-bottom: 3px;  //
      background-color: $metacity_bg_a;
      background-image: linear-gradient(to bottom,
                                        lighten($wm_bg_a, 2%) 50%,
                                        $wm_bg_a 50%,
                                        $primary_toolbar_bg_a);
      border-bottom: none;
    }
}

**Comment by ignisf** [comment]
:+1:
