### ISSUE TITLE
Fedora package does not use gtk2 theme properly

### ISSUE THREAD

**Issue by zauberlaus** [horst3180/Ceti-2-theme#9]
When installing the prebuilt Fedora package gtk2 apps do not use the theme. I had this issue with adwaita-dark as well and found a working package somewhere finally. An app where this issue appears is KeePassx
![bildschirmfoto von 2015-05-14 11 44 59](https://cloud.githubusercontent.com/assets/7562487/7629646/af4aa448-fa2e-11e4-8cb6-8cebc48cb4a3.png)

**Comment by horst3180** [comment]
The `global dark theme` setting in gnome-tweak-tool only affects GTK 3 applications. GTK 2 apps don't support this. The only solution would be to create a separate dark GTK 2 theme.
The thing is that Ceti wasn't designed as a global dark theme. I only created the dark GTK 3 theme to support the gnome applications which request a dark theme by default.
You could try [Vertex](https://github.com/horst3180/Vertex-theme) instead, if you haven't already. It has a global dark theme (GTK 2 included).

**Comment by zauberlaus** [comment]
Ah. i misunderstood this. Thank you! (Vertex is good :) )
